CREATE TABLE "answers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"play_id" uuid NOT NULL,
	"category_id" uuid NOT NULL,
	"answer" text NOT NULL,
	"rebuttaled" boolean DEFAULT false NOT NULL,
	"correct" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"category" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plays" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"score" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "answers"
ADD CONSTRAINT "answers_play_id_plays_id_fk" FOREIGN KEY ("play_id") REFERENCES "public"."plays"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "answers"
ADD CONSTRAINT "answers_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "answers_id_idx" ON "answers" USING btree ("id");
--> statement-breakpoint
CREATE INDEX "answers_play_id_idx" ON "answers" USING btree ("play_id");
--> statement-breakpoint
CREATE INDEX "answers_category_id_idx" ON "answers" USING btree ("category_id");
--> statement-breakpoint
CREATE INDEX "categories_id_idx" ON "categories" USING btree ("id");
--> statement-breakpoint
CREATE INDEX "plays_id_idx" ON "plays" USING btree ("id");
--> statement-breakpoint
CREATE INDEX "plays_timestamp_idx" ON "plays" USING btree ("timestamp");
--> statement-breakpoint
-- Seed data for categories table
INSERT INTO "categories" ("category")
VALUES ('A Boy''s Name'),
	('U.S. Cities'),
	('Things That Are Cold'),
	('School Supplies'),
	('Pro Sports Teams'),
	('Insects'),
	('Breakfast Foods'),
	('Furniture'),
	('T.V. Shows'),
	('Things That Are Found in the Ocean'),
	('Presidents'),
	('Product Names'),
	('Appliances'),
	('Types of Drink'),
	('Personality Traits'),
	('Articles of Clothing'),
	('Desserts'),
	('Car Parts'),
	('Things Found on a Map'),
	('Athletes'),
	('Items in a Refrigerator'),
	('Farm Animals'),
	('Street Names'),
	('Things on a Beach'),
	('Colors'),
	('Tools'),
	('A Girl''s Name'),
	('Villains/Monsters'),
	('Footwear'),
	('Something You''re Afraid Of'),
	('Terms of Measurement'),
	('Book Titles'),
	('Heroes'),
	('Gifts/Presents'),
	('Kinds of Dances'),
	('Things That Are Black'),
	('Vehicles'),
	('Tropical Locations'),
	('College Majors'),
	('Dairy Products'),
	('Things in a Souvenir Shop'),
	('Items in Your Purse/Wallet'),
	('Famous Females'),
	('Medicine/Drugs'),
	('Things Made of Metal'),
	('Hobbies'),
	('People in Uniform'),
	('Things You Plug In'),
	('Animals'),
	('Languages'),
	('Names Used in the Bible'),
	('Junk Food'),
	('Things That Grow'),
	('Companies'),
	('Video Games'),
	('Electronic Gadgets'),
	('Board Games'),
	('Things That Use a Remote'),
	('Card Games'),
	('Internet Lingo'),
	('Offensive Words'),
	('Wireless Things'),
	('Computer Parts'),
	('Software'),
	('Websites'),
	('Game Terms'),
	('Things in a Grocery Store'),
	('Reasons to Quit Your Job'),
	('Things That Have Stripes'),
	('Tourist Attractions'),
	('Diet Foods'),
	('Things Found in a Hospital'),
	('Food/Drink That Is Green'),
	('Weekend Activities'),
	('Acronyms'),
	('Seafood'),
	('Christmas Songs'),
	('Children''s Books'),
	('Things Found at a Bar'),
	('Sports Played Indoors'),
	('Names Used in Songs'),
	('Foods You Eat Raw'),
	('Places in Europe'),
	('Olympic Events'),
	('Things You See at the Zoo'),
	('Math Terms'),
	('Animals in Books or Movies'),
	('Things to Do at a Party'),
	('Sandwiches'),
	('Items in a Catalog'),
	('World Leaders/Politicians'),
	('School Subjects'),
	('Excuses for Being Late'),
	('Ice Cream Flavors'),
	('Things That Jump/Bounce'),
	('Television Stars'),
	('Things in a Park'),
	('Foreign Cities'),
	('Stones/Gems'),
	('Musical Instruments'),
	('Nicknames'),
	('Things in the Sky'),
	('Pizza Toppings'),
	('Colleges/Universities'),
	('Fish'),
	('Countries'),
	('Things That Have Spots'),
	('Historical Figures'),
	('Terms of Endearment'),
	('Items in This Room'),
	('Fictional Characters'),
	('Menu Items'),
	('Magazines'),
	('Capitals'),
	('Kinds of Candy'),
	('Items You Save Up to Buy'),
	('Something You Keep Hidden'),
	('Items in a Suitcase'),
	('Things With Tails'),
	('Sports Equipment'),
	('Crimes'),
	('Things That Are Sticky'),
	('Awards/Ceremonies'),
	('Cars'),
	('Spices/Herbs'),
	('Bad Habits'),
	('Cosmetics/Toiletries'),
	('Celebrities'),
	('Cooking Utensils'),
	('Reptiles/Amphibians'),
	('Parks'),
	('Leisure Activities'),
	('Things You''re Allergic To'),
	('Restaurants'),
	('Notorious People'),
	('Fruits'),
	('Things in a Medicine Cabinet'),
	('Toys'),
	('Household Chores'),
	('Bodies of Water'),
	('Authors'),
	('Halloween Costumes'),
	('Weapons'),
	('Things That Are Round'),
	('Words Associated With Exercise'),
	('Sports'),
	('Song Titles'),
	('Parts of the Body'),
	('Ethnic Foods'),
	('Things You Shout'),
	('Birds'),
	('Methods of Transportation'),
	('Items in a Kitchen'),
	('Flowers'),
	('Things You Replace'),
	('Famous Duos and Trios'),
	('Things Found in a Desk'),
	('Vacation Spots'),
	('Diseases'),
	('Words Associated With Money'),
	('Items in a Vending Machine'),
	('Movie Titles'),
	('Games'),
	('Things That You Wear'),
	('Beers'),
	('Things at a Circus'),
	('Vegetables'),
	('States'),
	('Things You Throw Away'),
	('Occupations'),
	('Cartoon Characters'),
	('Musical Groups'),
	('Store Names'),
	('Things at a Football Game'),
	('Trees'),
	('Kinds of Soup'),
	('Things Found in New York'),
	('Things You Get Tickets For'),
	('Things You Do at Work'),
	('Foreign Words Used in English'),
	('Things You Shouldn''t Touch'),
	('Spicy Foods'),
	('Things at a Carnival'),
	('Things You Make'),
	('Places to Hang Out'),
	('Honeymoon Spots'),
	('Things You Buy for Kids'),
	('Reasons to Take Out a Loan'),
	('Things to Do on a Date'),
	('Historic Events'),
	('Things You Do Every Day'),
	('Things You Get in the Mail'),
	('Things You Sit On'),
	('Reasons to Make a Phone Call'),
	('Titles People Can Have'),
	('Things That Have Buttons'),
	('Things That Have Wheels'),
	('Reasons to Call 911'),
	('Ways to Kill Time'),
	('Things That Can Get You Fired'),
	('Religion or belief system'),
	('Building material'),
	('Something you wish for'),
	('Things sold at a bakery'),
	('Surgical procedure'),
	('Candle scent'),
	('Constellations'),
	('Cleaning tools'),
	('First date locations'),
	('Gifts for a child'),
	('Type of Injury'),
	('Type of Music'),
	('Item in a classroom'),
	('Things at a Birthday Party'),
	('Things on a farm'),
	('Things at a thrift store'),
	('Reasons to stay home'),
	('Things you brag about');